const INVALID_PASSORD_OR_EMAIL = 'ER_0001';
const TOOKEN_EXPIRED_TIMEOUT = '10m';

const REFRESH_TOOKEN_EXPIRED_TIMEOUT = '50m';

module.exports = {
  INVALID_PASSORD_OR_EMAIL,
  TOOKEN_EXPIRED_TIMEOUT,
  REFRESH_TOOKEN_EXPIRED_TIMEOUT,
};
